import Foundation

let unit4Content = UnitContent(
    theory: [
        Topic(title: "1. The Turing Machine (TM)", content: "A Turing Machine was invented by Alan Turing in 1936. It is an abstract mathematical concept that arguably models the maximum limits of computation. Anything that can theoretically be computed by any modern computer, can be computed by a Turing Machine.\n\nA TM consists of:\n1. An Infinite Tape: Divided into discrete cells. Each cell contains a symbol from a finite alphabet, or a 'Blank' (B).\n2. A Tape Head: A read/write head that can scan a single cell at a time. It can read, write, and natively move Left (L) or Right (R).\n3. A State Control: A finite state machine that dictates instructions based on the current state and the symbol currently under the tape head.\n\nA transition is defined as: δ(q, a) = (p, b, D)\nMeaning: In state 'q', reading symbol 'a', transition to state 'p', write symbol 'b' on the tape, and move direction 'D' (Left or Right)."),
        Topic(title: "2. Turing Acceptability vs Decidability", content: "When a Turing Machine processes a string, three things can happen:\n1. It halts in an 'Accept' state.\n2. It halts in a 'Reject' state.\n3. It loops forever, never halting.\n\nRecursively Enumerable (RE) Languages:\nA language is RE (or Turing-Recognizable) if there exists a TM that will halt and Accept for all strings inside the language. However, if a string is NOT in the language, the TM might Reject, or it might loop indefinitely.\n\nRecursive (Decidable) Languages:\nA language is Recursive if there exists a TM that will ALWAYS eventually halt. It will definitively Accept strings in the language, and definitively Reject strings not in the language. It never loops infinitely."),
        Topic(title: "3. Variations of Turing Machines", content: "Computer scientists have tried to make 'stronger' Turing Machines by giving them more features. However, none of these variations add any actual computational power to the standard TM!\n\n1. Multi-tape TM: Has 2 or more separate infinite tapes with independent heads. Useful for copying/comparing, but anything a multi-tape TM can do, a single-tape TM can simulate (just much slower).\n2. Non-Deterministic TM: Can guess multiple paths simultaneously. Astonishingly, a standard Deterministic TM can simulate an NDTM by performing a breadth-first search of the NDTM's computation tree.\n3. TM with Two-way Infinite Tape: A tape that goes to infinity in both the left and right directions (as opposed to just right). Still equivalent."),
        Topic(title: "4. The Universal Turing Machine (UTM)", content: "Can we build a Turing Machine that can simulate ANY other Turing Machine?\n\nYes! Alan Turing described a Universal Turing Machine (UTM). It takes as input:\n1. An encoded description (source code) of an arbitrary Turing machine 'M'.\n2. An input string 'w' to be fed into 'M'.\n\nThe UTM simulates the behavior of 'M' running on 'w'. This is the foundational theoretical proof behind the concept of software. A computer (UTM) doesn't need its hardware rewired to perform a new task; it just needs new instructions (the encoded description of 'M') loaded into memory!")
    ],
    examples: [
        Topic(title: "Example: TM for a^n b^n c^n", content: "Remember, Pushdown Automata (with a stack) cannot handle a^n b^n c^n because you can't check the 'c's without losing track of the 'b's.\n\nTuring Machine Logic:\n1. Read 'a', replace it with 'X'. Move Right.\n2. Skip over remaining 'a's and 'Y's until you find a 'b'.\n3. Replace 'b' with 'Y'. Move Right.\n4. Skip over 'b's and 'Z's until you find a 'c'.\n5. Replace 'c' with 'Z'.\n6. Move Left all the way back until you hit 'X'. Move one space right.\n7. Repeat process. If all characters are converted to X, Y, Z, accept!"),
        Topic(title: "Example: TM for Finding Palindromes", content: "Input: '101' on infinite tape, surrounded by Blanks (B).\nTape: B 1 0 1 B\n\n1. Head reads '1'. Replaces with B. Remembers it saw a '1' by changing its state. Moves Right.\nTape: B B 0 1 B (Head moving right...)\n2. Keeps moving right until it hits a Blank (B). Steps one left.\n3. Checks if the symbol is '1'. It is! Replaces it with B. Moves Left.\nTape: B B 0 B B (Head moving left...)\n4. Keeps moving left until it hits a Blank. Steps one right. Re-starts process.\n5. If it finishes matching pairs symmetrically and the tape is empty, it Accept!"),
        Topic(title: "Example: TM as a function computer (f(x) = x + 1)", content: "A TM doesn't just accept/reject; it can compute functions.\nInput: Base-1 binary number (e.g., 5 = '11111').\nGoal: Add 1.\n\nLogic:\n1. Start at the leftmost '1'. Move Right until hitting Blank.\n2. Write a '1' at the blank space.\n3. Halt.\nThe machine started with 5 '1's, and the tape now holds 6 '1's. It successfully computed x + 1.")
    ],
    quizzes: [
        QuizQuestion(question: "A Turing Machine tape is:", options: ["Finite", "Infinite", "Read-only", "Write-only"], correctOptionIndex: 1, explanation: "A Turing Machine models boundless computation. The tape is mathematically boundless or 'infinite' in length, allowing for infinite memory reads/writes."),
        QuizQuestion(question: "Are Non-Deterministic TM strictly more powerful than Deterministic TM?", options: ["Yes", "No", "Only for exponential time", "Only for space complexity"], correctOptionIndex: 1, explanation: "Surprisingly, NO. Unlike NPDAs, any Non-Deterministic Turing Machine can be perfectly simulated by a standard Deterministic Turing Machine (albeit much slower)."),
        QuizQuestion(question: "Which language class is accepted by a Turing Machine that always halts?", options: ["Regular", "Context-Free", "Recursive", "Recursively Enumerable"], correctOptionIndex: 2, explanation: "If a Turing Machine is guaranteed to halt (never loop infinitely) for all strings, it formally accepts the 'Recursive (Decidable) Languages' class."),
        QuizQuestion(question: "What does a Universal Turing Machine simulate?", options: ["Only finite automata", "Any Turing machine and its input", "Only regular languages", "Only pushdown automata"], correctOptionIndex: 1, explanation: "A UTM takes an encoded description of ANY machine 'M', plus its input string 'w', and successfully simulates 'M' running on 'w'. This is the foundation of computer software files."),
        QuizQuestion(question: "TM can move its head in:", options: ["One direction only", "Both Left and Right", "Up and down", "None"], correctOptionIndex: 1, explanation: "By definition, a Turing Machine head has the freedom to dynamically traverse left (L) and right (R) to read and overwrite memory on the tape.")
    ]
)
