import Foundation

let unit5Content = UnitContent(
    theory: [
        Topic(title: "1. Decidability vs Undecidability", content: "In computer science, a 'Decision Problem' is a problem formulated as a yes/no question (e.g., 'Is x an even number?').\n\nDecidable Problem:\nA problem is decidable if an algorithm (a Turing Machine) exists that can definitively output 'YES' or 'NO' for every possible input in a finite amount of time.\n\nUndecidable Problem:\nA problem is undecidable if NO algorithm exists that can always guarantee a correct 'YES' or 'NO' answer for all inputs in finite time. The Turing Machine might occasionally loop indefinitely on some inputs."),
        Topic(title: "2. The Halting Problem", content: "The most famous undecidable problem, proven by Alan Turing in 1936.\n\nQuestion: Can you write a general computer program (let's call it 'H') that takes the source code of any other program ('P') and its input ('I'), and definitively tells you whether 'P' will eventually output an answer and halt, or if it will run in an infinite loop forever?\n\nTuring proved that this 'H' Program is mathematically impossible to write because it inherently leads to logical paradoxes."),
        Topic(title: "3. Post Correspondence Problem (PCP)", content: "PCP is a famous undecidable problem involving dominoes, invented by Emil Post.\n\nImagine you have a set of dominoes types. Each domino has a top string and a bottom string (e.g., top = 'a', bottom = 'ab'). You can use as many copies of each domino type as you want.\n\nGoal: Arrange a sequence of dominoes such that reading the top strings concatenation perfectly matches the bottom strings concatenation.\n\nIs there an algorithm that can look at ANY set of dominoes and tell you YES or NO if a match is possible? No. The problem is definitively undecidable."),
        Topic(title: "4. Complexity Classes: P vs NP", content: "While decidability asks 'Can it be solved at all?', Complexity asks 'Can it be solved efficiently?'\n\nP (Polynomial Time):\nThe class of decision problems that can be SOLVED quickly (in polynomial time like n^2) by a deterministic Turing Machine. (e.g., Sorting an array, checking if a graph is connected).\n\nNP (Non-Deterministic Polynomial Time):\nThe class of decision problems where, if you are given a potential solution, you can VERIFY if it is correct quickly (in polynomial time). However, solving it from scratch might take exponential time (e.g., Sudoku. Hard to solve, but if someone hands you a completed grid, it takes 1 second to verify if they did it right).\n\nThe greatest unsolved question in computer science: Does P = NP? (If we can quickly verify a solution, does a secret shortcut exist to also quickly find the solution?)"),
        Topic(title: "5. NP-Completeness and SAT", content: "A problem is classified as 'NP-Complete' if it is the hardest type of problem in the NP class.\nIf you find a fast (Polynomial-time) algorithm for just ONE NP-Complete problem, you instantly prove P = NP, and solve thousands of other NP problems instantly.\n\nStephen Cook and Leonid Levin independently proved that the 'Boolean Satisfiability Problem' (SAT) was the first NP-Complete problem. SAT asks: 'Given a complex boolean algebraic formula, is there any combination of True/False variables that makes the whole formula True?'")
    ],
    examples: [
        Topic(title: "Example: Proving the Halting Problem is Undecidable", content: "Let's assume the Halting Analyzer 'H(program, input)' exists. It perfectly returns 'HALTS' or 'LOOPS'.\n\nI will now write a troll program 'D' (The Destroyer). 'D' takes another program's code, asks 'H' what will happen, and does the exact opposite.\n\nCode for D:\nfunc D(code) {\n    if (H(code, code) == 'HALTS') {\n        while(true) {} // Loop forever intentionally\n    } else {\n        return // Halt intentionally\n    }\n}\n\nParadox Question: What happens if I pass D its own code? D(D)\n- If H says D will HALT... D enters the infinite loop.\n- If H says D will LOOP... D instantly halts.\n\nH is guaranteed to be wrong. Therefore, a perfect H cannot exist."),
        Topic(title: "Example: Solving a Post Correspondence Problem", content: "Given Dominoes:\nD1: Top='A', Bottom='ABA'\nD2: Top='ABA', Bottom='A'\n\nCan we find a match?\nTry sequence: D1, D2\nTop string: A + ABA = AABA\nBottom string: ABA + A = ABAA\nMismatch!\n\nThis specific subset is unsolvable, but a general algorithm cannot exist to prove all combinations."),
        Topic(title: "Example: P vs NP Real World Analogy", content: "The Traveling Salesman Problem (TSP).\nGiven a map of 50 cities, find the shortest possible route that visits every city once and returns home.\n\nStatus: NP-Hard.\n- VERIFYING (NP trait): If someone hands you a path and claims it's under 500 miles, you can easily add up the 50 distances in 10 seconds to verify.\n- SOLVING (P trait): To find the absolute shortest path, you might have to calculate 50! factorial routes, which would take supercomputers billions of years. ")
    ],
    quizzes: [
        QuizQuestion(question: "Which of the following is UNDECIDABLE?", options: ["Equivalence of two DFAs", "Halting Problem", "Whether a CFG generates empty string", "Whether a DFA accepts a string"], correctOptionIndex: 1, explanation: "Alan Turing famously proved the Halting Problem is formally undecidable because a machine attempting to analyze itself creates an infinite logical paradox."),
        QuizQuestion(question: "What does 'P' stand for in P vs NP?", options: ["Polynomial time", "Programmable", "Probabilistic", "Practical"], correctOptionIndex: 0, explanation: "P represents problems that can be solved quickly in 'Polynomial time' (e.g. O(n^2)) using a standard Deterministic Turing Machine."),
        QuizQuestion(question: "If an NP-Complete problem is solved in polynomial time, then:", options: ["P = NP", "P != NP", "NP = EXPTIME", "None of the above"], correctOptionIndex: 0, explanation: "If even a single NP-Complete problem is solved in Polynomial Time (P), then logically ALL problems in NP can be reduced and solved in Polynomial Time, proving P = NP."),
        QuizQuestion(question: "Post Correspondence Problem (PCP) is:", options: ["Decidable", "Undecidable", "NP-Complete", "In P"], correctOptionIndex: 1, explanation: "PCP (often visualized as matching domino tiles) is an undecidable problem over string concatenations without relying on Turing Machine models."),
        QuizQuestion(question: "The first problem proven to be NP-complete was:", options: ["Knapsack", "Traveling Salesman Problem", "Boolean Satisfiability (SAT)", "Vertex Cover"], correctOptionIndex: 2, explanation: "Through the Cook-Levin Theorem, the Boolean Satisfiability (SAT) problem was historically the first mathematical problem proven to be NP-Complete.")
    ]
)
